#!/usr/bin/env bash

if ! which openssl &>/dev/null; then
    echo no openssl found, exiting...
    exit 1
fi

for f in $*; do
    echo processing $f ...
    newname=$(openssl rand -hex 32)

    if mv $f $newname; then
        echo renamed to $newname
    else
        echo ERROR renaming to $newname
    fi
done
